ticket 8 bundled fix (sys/* includes, v4l dependency, autools update
git-svn-id: svn://code.dyne.org/veejay/trunk@219 eb8d1916-c9e9-0310-b8de-cf0c9472ead5

diff --git a/veejay-current/configure b/veejay-current/configure
--- a/veejay-current/configure
+++ b/veejay-current/configure
@@ -469,7 +469,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all ffmpeg/ffmpeg"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CCAS CCASFLAGS CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP EGREP LT_RELEASE LT_CURRENT LT_REVISION LT_AGE LN_S RANLIB ac_ct_RANLIB ECHO LIBTOOL PRID64_STRING_FORMAT LIBGETOPT_LIB LIBOBJS POW_LIB LIBM_LIBS GLIB_CONFIG GLIB_CFLAGS GLIB_LIBS PTHREAD_LIBS JPEG_LIBS JPEG_CFLAGS DV_LIBS DV_CFLAGS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS x_libraries V4LCONF_LIBS SDL_CONFIG SDL_CFLAGS SDL_LIBS PKG_CONFIG DIRECTFB_CFLAGS DIRECTFB_LIBS JACK_CFLAGS JACK_LIBS SAMPLERATE_CFLAGS SAMPLERATE_LIBS XML2_CONFIG XML_CPPFLAGS XML_LIBS FREETYPE_CONFIG FT_LIBS FT_LDFLAGS FT_CFLAGS VEVO_CONFIG VEVO_CFLAGS  VEVO_LIBS  AS ASFLAGS HAVE_FREETYPE_TRUE HAVE_FREETYPE_FALSE HAVE_VEVO_TRUE HAVE_VEVO_FALSE BUILD_VEEJAY_TRUE BUILD_VEEJAY_FALSE HAVE_ASM_MMX_TRUE HAVE_ASM_MMX_FALSE HAVE_ASM_MMX2_TRUE HAVE_ASM_MMX2_FALSE HAVE_ASM_SSE_TRUE HAVE_ASM_SSE_FALSE HAVE_ASM_NASM_TRUE HAVE_ASM_NASM_FALSE HAVE_ASM_CMOV_TRUE HAVE_ASM_CMOV_FALSE HAVE_X86CPU_TRUE HAVE_X86CPU_FALSE ARCH_X86_TRUE ARCH_X86_FALSE HAVE_PPCCPU_TRUE HAVE_PPCCPU_FALSE HAVE_MIPS_TRUE HAVE_MIPS_FALSE HAVE_SDL_TRUE HAVE_SDL_FALSE HAVE_XML2_TRUE HAVE_XML2_FALSE HAVE_V4L_TRUE HAVE_V4L_FALSE HAVE_DIRECTFB_TRUE HAVE_DIRECTFB_FALSE HAVE_JACK_TRUE HAVE_JACK_FALSE HAVE_SAMPLERATE_TRUE HAVE_SAMPLERATE_FALSE ARCH_PPC_TRUE ARCH_PPC_FALSE CAN_COMPILE_C_ALTIVEC_TRUE CAN_COMPILE_C_ALTIVEC_FALSE LIBDV_PRE_0_9_9_TRUE LIBDV_PRE_0_9_9_FALSE HAVE_MMX_TRUE HAVE_MMX_FALSE SYSTEM_DARWIN_TRUE SYSTEM_DARWIN_FALSE HAVE_PPC_ALTIVEC_TRUE HAVE_PPC_ALTIVEC_FALSE WHAT subdirs LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CCAS CCASFLAGS CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP EGREP LT_RELEASE LT_CURRENT LT_REVISION LT_AGE LN_S RANLIB ac_ct_RANLIB ECHO LIBTOOL PRID64_STRING_FORMAT LIBGETOPT_LIB LIBOBJS POW_LIB LIBM_LIBS GLIB_CONFIG GLIB_CFLAGS GLIB_LIBS PTHREAD_LIBS JPEG_LIBS JPEG_CFLAGS DV_LIBS DV_CFLAGS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS x_libraries V4LCONF_LIBS SDL_CONFIG SDL_CFLAGS SDL_LIBS PKG_CONFIG DIRECTFB_CFLAGS DIRECTFB_LIBS JACK_CFLAGS JACK_LIBS SAMPLERATE_CFLAGS SAMPLERATE_LIBS XML2_CONFIG XML_CPPFLAGS XML_LIBS FREETYPE_CONFIG FT_LIBS FT_LDFLAGS FT_CFLAGS VEVO_CONFIG VEVO_CFLAGS  VEVO_LIBS  AS ASFLAGS HAVE_FREETYPE_TRUE HAVE_FREETYPE_FALSE HAVE_VEVO_TRUE HAVE_VEVO_FALSE BUILD_VEEJAY_TRUE BUILD_VEEJAY_FALSE HAVE_ASM_MMX_TRUE HAVE_ASM_MMX_FALSE HAVE_ASM_MMX2_TRUE HAVE_ASM_MMX2_FALSE HAVE_ASM_SSE_TRUE HAVE_ASM_SSE_FALSE HAVE_ASM_NASM_TRUE HAVE_ASM_NASM_FALSE HAVE_ASM_CMOV_TRUE HAVE_ASM_CMOV_FALSE HAVE_X86CPU_TRUE HAVE_X86CPU_FALSE ARCH_X86_TRUE ARCH_X86_FALSE HAVE_PPCCPU_TRUE HAVE_PPCCPU_FALSE HAVE_MIPS_TRUE HAVE_MIPS_FALSE HAVE_UNION_SEMUN_TRUE HAVE_UNION_SEMUN_FALSE HAVE_SDL_TRUE HAVE_SDL_FALSE HAVE_XML2_TRUE HAVE_XML2_FALSE HAVE_V4L_TRUE HAVE_V4L_FALSE HAVE_DIRECTFB_TRUE HAVE_DIRECTFB_FALSE HAVE_JACK_TRUE HAVE_JACK_FALSE HAVE_SAMPLERATE_TRUE HAVE_SAMPLERATE_FALSE ARCH_PPC_TRUE ARCH_PPC_FALSE CAN_COMPILE_C_ALTIVEC_TRUE CAN_COMPILE_C_ALTIVEC_FALSE LIBDV_PRE_0_9_9_TRUE LIBDV_PRE_0_9_9_FALSE HAVE_MMX_TRUE HAVE_MMX_FALSE SYSTEM_DARWIN_TRUE SYSTEM_DARWIN_FALSE HAVE_PPC_ALTIVEC_TRUE HAVE_PPC_ALTIVEC_FALSE WHAT subdirs LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -4884,6 +4884,7 @@ have_cmov=false
 have_asm_3dnow=false
 have_asm_mmx2=false
 have_x86cpu=false
+have_union_semun=false
 have_mips=false
 have_ppccpu=false
 have_ppc_altivec=false
@@ -6258,7 +6259,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6261 "configure"' > conftest.$ac_ext
+  echo '#line 6262 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6787,7 +6788,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:6790: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:6791: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -8619,7 +8620,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8622 "configure"
+#line 8623 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8717,7 +8718,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8720 "configure"
+#line 8721 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21398,6 +21399,53 @@ else
   have_cmov=false
 fi
 
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/types.h>
+#include <sys/ipc.h>
+#include <sys/sem.h>
+int
+main ()
+{
+union semun foo;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_semun=true
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+have_semun=false
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+if test x$have_semun = xtrue
+then
+	cat >>confdefs.h <<\_ACEOF
+#define HAVE_UNION_SEMUN 1
+_ACEOF
+
+fi
+
+
 
 
 if test x$have_freetype = xtrue; then
@@ -21516,6 +21564,16 @@ if test x$have_mips = xtrue; then
 else
   HAVE_MIPS_TRUE='#'
   HAVE_MIPS_FALSE=
+fi
+
+
+
+if test x$have_semun = xtrue; then
+  HAVE_UNION_SEMUN_TRUE=
+  HAVE_UNION_SEMUN_FALSE='#'
+else
+  HAVE_UNION_SEMUN_TRUE='#'
+  HAVE_UNION_SEMUN_FALSE=
 fi
 
 
@@ -21941,6 +21999,13 @@ if test -z "${HAVE_MIPS_TRUE}" && test -z "${HAVE_MIPS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_MIPS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"HAVE_MIPS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_UNION_SEMUN_TRUE}" && test -z "${HAVE_UNION_SEMUN_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_UNION_SEMUN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_UNION_SEMUN\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -22715,6 +22780,8 @@ s,@HAVE_PPCCPU_TRUE@,$HAVE_PPCCPU_TRUE,;t t
 s,@HAVE_PPCCPU_FALSE@,$HAVE_PPCCPU_FALSE,;t t
 s,@HAVE_MIPS_TRUE@,$HAVE_MIPS_TRUE,;t t
 s,@HAVE_MIPS_FALSE@,$HAVE_MIPS_FALSE,;t t
+s,@HAVE_UNION_SEMUN_TRUE@,$HAVE_UNION_SEMUN_TRUE,;t t
+s,@HAVE_UNION_SEMUN_FALSE@,$HAVE_UNION_SEMUN_FALSE,;t t
 s,@HAVE_SDL_TRUE@,$HAVE_SDL_TRUE,;t t
 s,@HAVE_SDL_FALSE@,$HAVE_SDL_FALSE,;t t
 s,@HAVE_XML2_TRUE@,$HAVE_XML2_TRUE,;t t
